[[sources]]
name = "friendly-snippets"
git = "https://github.com/rafamadriz/friendly-snippets.git"

[[sources.paths]]
scope = ["nix"]
path = "snippets/nix.json"

[[sources.paths]]
scope = ["go"]
path = "snippets/go.json"

[[sources.paths]]
scope = ["java"]
path = "snippets/java/java.json"

[[sources.paths]]
scope = ["rust"]
path = "snippets/rust/rust.json"

[[sources.paths]]
scope = ["shellscript"]
path = "snippets/shell/shell.json"
