[[snippets]]
prefix = "rust"
scope = [ "toml" ]
description = "Rust toolchain definition"
body = """
[toolchain]
channel = "${1:stable}"
components = [ "rustc", "cargo", "clippy", "rustfmt", "rust-src", "rust-analyzer" ]"""
