[colors]
badge_text_dark = '#000000'
badge_text_light = '#000000'
blue_dark = '#1E90FF'
blue_light = '#1E90FF'
green_dark = '#02BF87'
green_light = '#02BA84'
indigo_dark = '#7571F9'
indigo_light = '#5A56E0'
orange_dark = '#FFA336'
orange_light = '#FFB733'
red_dark = '#FE5F86'
red_light = '#FE5F86'
vividred_dark = '#FE134D'
vividred_light = '#FE134D'
yellow_dark = '#CCCC00'
yellow_light = '#CCCC00'

[colors.form]
theme = 'Base16'

[git]
default_branch = 'main'

[git.remote]
enable = false
name = 'origin'

[jj]
colocate = true
default_branch = 'main'

[jj.remote]
colocate = false
enable = true
name = 'origin'
url = 'git@github.com:drlucaa/todo.git'

[storage]
path = '/home/luca/.yatto'

[vcs]
backend = 'jj'

